services:
  db:
    image: mysql/mysql-server
    container_name: db-container
    ports:
      - "33061:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_DATABASE=${DB_NAME}"
    networks:
      - leboncoin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 45s
      interval: 5s
      retries: 10
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  app:
    build: 
      context: .
      dockerfile: ./Containerfile

    container_name: app-container
    volumes:
      - ".:/app"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - leboncoin

networks:
  leboncoin:
    driver: bridge
